name: Meu primeiro workflow

on: push

jobs:
  primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Este job foi criado por causa do ${{ github.event_name }}."
      - run: echo "ğŸ§ Este job estÃ¡ rodando no servidor ${{ runner.os }} diretamente no Github!"
      - run: echo "ğŸ” O nome da sua branch Ã© ${{ github.ref }} e sua repo Ã© ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ A repo ${{ github.repository }} foi clonada para a esteira."
      - run: echo "ğŸ–¥ï¸ O workflow estÃ¡ pronto para rodar o cÃ³digo."
      - name: Lista de arquivos no repositÃ³rio
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ O status deste job Ã© ${{ job.status }}."

  job-de-teste:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalando o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - run: echo "ğŸ‰ Este job foi criado por causa do ${{ github.event_name }}."
      - run: echo "ğŸ§ Este job estÃ¡ rodando no servidor ${{ runner.os }} diretamente no Github!"
      - run: echo "ğŸ” O nome da sua branch Ã© ${{ github.ref }} e sua repo Ã© ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Mostrando a versÃ£o do Python
        run: python -c "import sys; print(sys.version)"
      - name: Teste com Pytest
        run: |
          pip install pytest pytest-cov
          pytest tests/test_geometria.py
      - run: echo "ğŸ O status deste job Ã© ${{ job.status }}."